name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: touch
      run: touch onefile
    - name: run ls
      run: ls -alh
    - name: run ls auto
      run: ls -alh --color=auto
    - name: run ls always
      run: ls -alh --color=always
