name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - master

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: build docs
        run: mkdir -p docs && echo "docs for $(basename ${GITHUB_REF}) built on $(date -Ru)" > docs/index.html
      - name: commit docs
        run: git checkout gh-pages && mv docs $(basename ${GITHUB_REF}) && git add . && git commit -a -m "update docs"
      - name: debug
        run: echo $GITHUB_REF
