name: release

on:
  release:
    types:
      - published

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Ansible
        run: pip install --upgrade ansible
      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v1.0.10
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
