name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - master

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: build docs
        run: mkdir -p docs && echo "docs for $(basename ${GITHUB_REF}) built on $(date -Ru)" > docs/index.html
      - name: commit docs
        run: git checkout gh-pages && mv docs $(basename ${GITHUB_REF}) && dirname */index.html | sort --version-sort | xargs -I@@ -n1 echo '<a href="@@/">@@</a><br/>' > index.html && git add . && git commit -a -m "update docs"
      - name: push docs
        run: git push origin gh-pages
